version: '3.7'
services:
  jvm:
    build:
      context: ./
      dockerfile: ./docker/jvm/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb_container
  mongodb_container:
    # mongodb://root:rootpassword@localhost:27017/app_versions
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=AppVersions
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/docker/data/db
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongodb_data_container: